/**
 * Canonical list of rule IDs emitted by the Go Visa rule engine.
 *
 * Use `RULE_IDS.<NAME>` ao emitir findings — não use literais.
 * Isso permite type-checking ao adicionar/renomear regras e facilita
 * busca cross-codebase (UI, analytics, feedback).
 */
export const RULE_IDS = {
  // ----- T-visa Filing (tier1) -----
  T_FILING_PHYSICAL_ADDR_NOT_GOVISA: "T_FILING_PHYSICAL_ADDR_NOT_GOVISA",
  T_FILING_PHYSICAL_ADDR_OK_BY_PROOF: "T_FILING_PHYSICAL_ADDR_OK_BY_PROOF",
  T_FILING_PHYSICAL_ADDR_NEEDS_PROOF: "T_FILING_PHYSICAL_ADDR_NEEDS_PROOF", // legado, não emitir
  T_FILING_PHYSICAL_ADDR_MISMATCH_PROOF: "T_FILING_PHYSICAL_ADDR_MISMATCH_PROOF",
  T_FILING_PHYSICAL_ADDR_PROOF_MISSING: "T_FILING_PHYSICAL_ADDR_PROOF_MISSING",
  // Item 2 (10/06): I-192 Part 2 item 10 é a fonte definitiva do endereço atual
  T_FILING_PHYSICAL_ADDR_DIVERGE_I192: "T_FILING_PHYSICAL_ADDR_DIVERGE_I192",
  T_FILING_SAFE_MAILING_NOT_GOVISA: "T_FILING_SAFE_MAILING_NOT_GOVISA",
  T_FILING_IN_CARE_OF_MISSING: "T_FILING_IN_CARE_OF_MISSING",
  T_FILING_MAILING_NOT_GOVISA: "T_FILING_MAILING_NOT_GOVISA",
  T_FILING_PERSON_FAMILY_NAME_EMPTY: "T_FILING_PERSON_FAMILY_NAME_EMPTY",
  T_FILING_PERSON_GIVEN_NAME_EMPTY: "T_FILING_PERSON_GIVEN_NAME_EMPTY",
  T_FILING_PERSON_DOB_EMPTY: "T_FILING_PERSON_DOB_EMPTY",
  T_FILING_PERSON_BIRTH_COUNTRY_EMPTY: "T_FILING_PERSON_BIRTH_COUNTRY_EMPTY",
  T_FILING_PERSON_PASSPORT_EMPTY: "T_FILING_PERSON_PASSPORT_EMPTY",
  T_FILING_SSN_EMPTY: "T_FILING_SSN_EMPTY",
  T_FILING_APPLICANT_SIG_MISSING: "T_FILING_APPLICANT_SIG_MISSING",
  T_FILING_INTERPRETER_SIG_MISSING: "T_FILING_INTERPRETER_SIG_MISSING",
  T_FILING_PREPARER_SIG_MISSING: "T_FILING_PREPARER_SIG_MISSING",
  T_FILING_G28_CLIENT_SIG_MISSING: "T_FILING_G28_CLIENT_SIG_MISSING",
  T_FILING_G28_ATTORNEY_SIG_MISSING: "T_FILING_G28_ATTORNEY_SIG_MISSING",
  T_FILING_DRAFT_MODE_NOTICE: "T_FILING_DRAFT_MODE_NOTICE",
  T_FILING_I765_CATEGORY_EMPTY: "T_FILING_I765_CATEGORY_EMPTY",
  T_FILING_I765_CATEGORY_INVALID_FOR_T1: "T_FILING_I765_CATEGORY_INVALID_FOR_T1",
  T_FILING_I765_NAME_DIVERGES: "T_FILING_I765_NAME_DIVERGES",
  T_FILING_I914B_PART2_PREFILLED: "T_FILING_I914B_PART2_PREFILLED",
  T_FILING_I914B_OFFICER_SIG_MISSING: "T_FILING_I914B_OFFICER_SIG_MISSING",

  // ----- T-visa Substantivo (tier2) -----
  T_SUBST_NO_FORCE_FRAUD_COERCION: "T_SUBST_NO_FORCE_FRAUD_COERCION",
  T_SUBST_TRAFFICKING_TYPE_UNCLEAR: "T_SUBST_TRAFFICKING_TYPE_UNCLEAR",
  T_SUBST_NO_PHYSICAL_PRESENCE_NEXUS: "T_SUBST_NO_PHYSICAL_PRESENCE_NEXUS",
  T_SUBST_HARDSHIP_ABSENT: "T_SUBST_HARDSHIP_ABSENT",
  T_SUBST_TRAUMA_UNDERDESCRIBED: "T_SUBST_TRAUMA_UNDERDESCRIBED",
  T_SUBST_COOPERATION_NO_I914B_NO_EXEMPTION: "T_SUBST_COOPERATION_NO_I914B_NO_EXEMPTION",
  T_SUBST_COOPERATION_EXEMPTION_DOCS_NEEDED: "T_SUBST_COOPERATION_EXEMPTION_DOCS_NEEDED",
  T_SUBST_I192_EWI_GROUND_MISSING: "T_SUBST_I192_EWI_GROUND_MISSING",
  T_SUBST_I192_NO_WAIVER_JUSTIFICATION: "T_SUBST_I192_NO_WAIVER_JUSTIFICATION",
  T_SUBST_I914B_AGENCY_NOT_QUALIFYING: "T_SUBST_I914B_AGENCY_NOT_QUALIFYING",
  T_SUBST_REMOVAL_PROCEEDINGS: "T_SUBST_REMOVAL_PROCEEDINGS",
  T_SUBST_PRIOR_APPLICATIONS: "T_SUBST_PRIOR_APPLICATIONS",

  // ----- T-visa Consistency (intra/cross cluster) -----
  T_CONS_DOB_FORMS_DIVERGE: "T_CONS_DOB_FORMS_DIVERGE",
  T_CONS_NAME_FORMS_DIVERGE: "T_CONS_NAME_FORMS_DIVERGE",
  T_CONS_PASSPORT_NUMBER_DIVERGE: "T_CONS_PASSPORT_NUMBER_DIVERGE",
  T_CONS_PASSPORT_NUMBER_IMG_VS_FORM: "T_CONS_PASSPORT_NUMBER_IMG_VS_FORM",
  T_CONS_MARITAL_DIVERGE: "T_CONS_MARITAL_DIVERGE",
  T_CONS_BIRTH_COUNTRY_DIVERGE: "T_CONS_BIRTH_COUNTRY_DIVERGE",
  T_CONS_ANUMBER_DIVERGE: "T_CONS_ANUMBER_DIVERGE",
  T_CONS_ANUMBER_SSN_EXTRACTOR_SWAP: "T_CONS_ANUMBER_SSN_EXTRACTOR_SWAP",
  T_CONS_DOB_STORY_FORM_DIVERGE: "T_CONS_DOB_STORY_FORM_DIVERGE",
  T_CONS_PASSPORT_STORY_FORM_DIVERGE: "T_CONS_PASSPORT_STORY_FORM_DIVERGE",
  T_CONS_MARITAL_STORY_FORM_DIVERGE: "T_CONS_MARITAL_STORY_FORM_DIVERGE",
  T_CONS_ENTRY_YEAR_DIVERGE: "T_CONS_ENTRY_YEAR_DIVERGE",
  T_CONS_PORT_OF_ENTRY_DIVERGE: "T_CONS_PORT_OF_ENTRY_DIVERGE",
  T_CONS_SPOUSE_FLAG_DIVERGE: "T_CONS_SPOUSE_FLAG_DIVERGE",
  T_CONS_CHILD_NAME_VS_I914A: "T_CONS_CHILD_NAME_VS_I914A",
  T_CONS_CHILD_DOB_VS_I914A: "T_CONS_CHILD_DOB_VS_I914A",
  T_CONS_TRAFFICKER_NAME_VS_WITNESS: "T_CONS_TRAFFICKER_NAME_VS_WITNESS",

  // ----- T-visa Dependents -----
  T_DEP_QUALIFYING_CHILD_NO_I914A: "T_DEP_QUALIFYING_CHILD_NO_I914A",
  T_DEP_USC_CHILD_NO_I914A_OK: "T_DEP_USC_CHILD_NO_I914A_OK",
  T_DEP_NON_US_CHILD_NO_I914A_OK: "T_DEP_NON_US_CHILD_NO_I914A_OK",
  T_DEP_NON_QUALIFYING_FAMILY_MEMBER_OK: "T_DEP_NON_QUALIFYING_FAMILY_MEMBER_OK",
  T_DEP_FAMILY_MEMBER_REL_DIFF_AGE_SUSPICIOUS: "T_DEP_FAMILY_MEMBER_REL_DIFF_AGE_SUSPICIOUS",
  T_DEP_MARITAL_STATUS_NO_SPOUSE_DEP: "T_DEP_MARITAL_STATUS_NO_SPOUSE_DEP",
  T_DEP_I914A_REL_MISSING: "T_DEP_I914A_REL_MISSING",
  T_DEP_I914A_NO_EVIDENCE: "T_DEP_I914A_NO_EVIDENCE",
  T_DEP_I914A_ABROAD_CONSULAR: "T_DEP_I914A_ABROAD_CONSULAR",
  T_DEP_CHILDREN_UNKNOWN_AGE: "T_DEP_CHILDREN_UNKNOWN_AGE",
  T_DEP_NON_QUALIFYING_KIDS_OK: "T_DEP_NON_QUALIFYING_KIDS_OK",

  // ----- Documents (cross-case) -----
  DOC_PASSPORT_SIG_MISSING: "DOC_PASSPORT_SIG_MISSING",
  DOC_PASSPORT_SIG_AMBIGUOUS: "DOC_PASSPORT_SIG_AMBIGUOUS",
  DOC_PASSPORT_NUMBER_IMG_VS_FORM: "DOC_PASSPORT_NUMBER_IMG_VS_FORM",
  DOC_PASSPORT_DOB_VS_FORM: "DOC_PASSPORT_DOB_VS_FORM",
  DOC_PASSPORT_FAMILY_NAME_VS_FORM: "DOC_PASSPORT_FAMILY_NAME_VS_FORM",
  DOC_PASSPORT_GIVEN_NAME_VS_FORM: "DOC_PASSPORT_GIVEN_NAME_VS_FORM",
  DOC_PASSPORT_BIRTH_PLACE_VS_FORM: "DOC_PASSPORT_BIRTH_PLACE_VS_FORM",
  DOC_PASSPORT_NATIONALITY_VS_FORM: "DOC_PASSPORT_NATIONALITY_VS_FORM",
  DOC_PASSPORT_SEX_VS_FORM: "DOC_PASSPORT_SEX_VS_FORM",
  DOC_PASSPORT_ISSUING_COUNTRY_VS_FORM: "DOC_PASSPORT_ISSUING_COUNTRY_VS_FORM",
  DOC_PASSPORT_EXPIRATION_VS_FORM: "DOC_PASSPORT_EXPIRATION_VS_FORM",
  DOC_PASSPORT_EXPIRED: "DOC_PASSPORT_EXPIRED",
  DOC_PASSPORT_QUALITY_ISSUES: "DOC_PASSPORT_QUALITY_ISSUES",
  DOC_PROOF_OF_ADDRESS_HOLDER_MISMATCH: "DOC_PROOF_OF_ADDRESS_HOLDER_MISMATCH",
  DOC_WITNESS_NOT_FOUND: "DOC_WITNESS_NOT_FOUND",
  DOC_WITNESS_NO_SIG: "DOC_WITNESS_NO_SIG",
  DOC_WITNESS_NO_PERJURY: "DOC_WITNESS_NO_PERJURY",
  DOC_WITNESS_VAGUE: "DOC_WITNESS_VAGUE",
  DOC_WITNESS_OTHER_CONCERN: "DOC_WITNESS_OTHER_CONCERN",
  DOC_MEDICAL_NOT_FOUND: "DOC_MEDICAL_NOT_FOUND",
  DOC_MEDICAL_NOT_LICENSED: "DOC_MEDICAL_NOT_LICENSED",
  DOC_MEDICAL_NO_DSM5: "DOC_MEDICAL_NO_DSM5",
  DOC_MEDICAL_NO_NEXUS: "DOC_MEDICAL_NO_NEXUS",
  DOC_MEDICAL_NO_TRAUMA_FIT: "DOC_MEDICAL_NO_TRAUMA_FIT",
  DOC_COUNTRY_NOT_RELEVANT: "DOC_COUNTRY_NOT_RELEVANT",
  DOC_COUNTRY_NO_RETRAFFICKING: "DOC_COUNTRY_NO_RETRAFFICKING",
  DOC_COUNTRY_NO_MENTAL_HEALTH: "DOC_COUNTRY_NO_MENTAL_HEALTH",
  DOC_COUNTRY_OBSERVATIONS: "DOC_COUNTRY_OBSERVATIONS",
  DOC_COUNTRY_WRONG_COUNTRY: "DOC_COUNTRY_WRONG_COUNTRY",
  DOC_TRANSLATION_MISSING: "DOC_TRANSLATION_MISSING",
  DOC_TRANSLATION_OBSERVATIONS: "DOC_TRANSLATION_OBSERVATIONS",

  // ----- U-visa -----
  U_FILING_I918_MISSING: "U_FILING_I918_MISSING",
  U_FILING_I918B_OFFICER_TITLE_EMPTY: "U_FILING_I918B_OFFICER_TITLE_EMPTY",
  U_FILING_I918B_NOT_SIGNED: "U_FILING_I918B_NOT_SIGNED",
  U_SUBST_I918B_MISSING_NO_WAIVER: "U_SUBST_I918B_MISSING_NO_WAIVER",
  U_SUBST_I918B_MISSING_WITH_WAIVER: "U_SUBST_I918B_MISSING_WITH_WAIVER",
  U_SUBST_I918B_AGENCY_NOT_QUALIFYING: "U_SUBST_I918B_AGENCY_NOT_QUALIFYING",
  U_SUBST_I918B_HELPFULNESS_MISSING: "U_SUBST_I918B_HELPFULNESS_MISSING",
  U_SUBST_I918B_OLD: "U_SUBST_I918B_OLD",
  U_SUBST_NO_QUALIFYING_CRIME: "U_SUBST_NO_QUALIFYING_CRIME",
  U_SUBST_NO_SUBSTANTIAL_ABUSE: "U_SUBST_NO_SUBSTANTIAL_ABUSE",
  U_SUBST_LOW_ABUSE_EXAMPLES: "U_SUBST_LOW_ABUSE_EXAMPLES",
  U_SUBST_NO_COOPERATION: "U_SUBST_NO_COOPERATION",
  U_SUBST_CRIME_NOT_QUALIFYING: "U_SUBST_CRIME_NOT_QUALIFYING",
  U_CONS_CRIME_I918_VS_I918B: "U_CONS_CRIME_I918_VS_I918B",
  U_CONS_VICTIM_NAME_DIVERGE: "U_CONS_VICTIM_NAME_DIVERGE",
  U_DEP_I918A_PRINCIPAL_NAME_DIVERGE: "U_DEP_I918A_PRINCIPAL_NAME_DIVERGE",
  U_DEP_I918A_NO_QUALIFYING_REL: "U_DEP_I918A_NO_QUALIFYING_REL",
  U_DEP_I918A_NO_EVIDENCE: "U_DEP_I918A_NO_EVIDENCE",
  // Cliente cita dependente qualificante na I-918 (ou story) sem I-918A correspondente.
  U_DEP_QUALIFYING_RELATIVE_NO_I918A: "U_DEP_QUALIFYING_RELATIVE_NO_I918A",
  U_DEP_USC_NO_I918A_OK: "U_DEP_USC_NO_I918A_OK",
  U_DEP_ABROAD_CONSULAR_OK: "U_DEP_ABROAD_CONSULAR_OK",

  // ----- VAWA -----
  V_FILING_I360_MISSING: "V_FILING_I360_MISSING",
  V_FILING_RELATIONSHIP_MISSING: "V_FILING_RELATIONSHIP_MISSING",
  V_FILING_GMC_DECLARATION_MISSING: "V_FILING_GMC_DECLARATION_MISSING",
  V_SUBST_ABUSER_STATUS_UNKNOWN: "V_SUBST_ABUSER_STATUS_UNKNOWN",
  V_SUBST_DIVORCE_OUTSIDE_WINDOW: "V_SUBST_DIVORCE_OUTSIDE_WINDOW",
  V_SUBST_NO_RESIDENCE: "V_SUBST_NO_RESIDENCE",
  V_SUBST_NO_BATTERY_CRUELTY: "V_SUBST_NO_BATTERY_CRUELTY",
  V_SUBST_LOW_ABUSE_EXAMPLES: "V_SUBST_LOW_ABUSE_EXAMPLES",
  V_SUBST_NO_GOOD_FAITH_INDICATORS: "V_SUBST_NO_GOOD_FAITH_INDICATORS",
  V_SUBST_GMC_CONCERNS: "V_SUBST_GMC_CONCERNS",
  V_CONS_MARRIAGE_DATE_DIVERGE: "V_CONS_MARRIAGE_DATE_DIVERGE",
  V_CONS_ABUSER_NAME_DIVERGE: "V_CONS_ABUSER_NAME_DIVERGE",
  V_CONS_CHILD_VS_I360_CHILDREN_INCLUDED: "V_CONS_CHILD_VS_I360_CHILDREN_INCLUDED",

  // ----- Q6 — Edição USCIS desatualizada (genérico, válido p/ T/U/VAWA) -----
  DOC_EDITION_OUTDATED: "DOC_EDITION_OUTDATED",

  // ----- Q9 — CSPA age-out risk (faixa 20-21 anos no filing) -----
  T_DEP_CSPA_AGE_OUT_RISK: "T_DEP_CSPA_AGE_OUT_RISK",
  U_DEP_CSPA_AGE_OUT_RISK: "U_DEP_CSPA_AGE_OUT_RISK",
  V_DEP_CSPA_AGE_OUT_RISK: "V_DEP_CSPA_AGE_OUT_RISK",

  // ----- Q10 — I-192 inadmissibility checklist -----
  T_SUBST_I192_CRIMINAL_GROUND_MISSING: "T_SUBST_I192_CRIMINAL_GROUND_MISSING",
  T_SUBST_I192_PRIOR_REMOVAL_GROUND_MISSING: "T_SUBST_I192_PRIOR_REMOVAL_GROUND_MISSING",
  T_SUBST_I192_FRAUD_GROUND_PROBABLY_NEEDED: "T_SUBST_I192_FRAUD_GROUND_PROBABLY_NEEDED",

  // ----- Q11 — Continuous Physical Presence (T-visa) -----
  T_SUBST_CPP_BROKEN_RISK: "T_SUBST_CPP_BROKEN_RISK",
  T_SUBST_CPP_LONG_GAP: "T_SUBST_CPP_LONG_GAP",

  // ----- Q12 — Bona fide marriage timing (VAWA) -----
  V_SUBST_BONA_FIDE_TIMING_SUSPECT: "V_SUBST_BONA_FIDE_TIMING_SUSPECT",

  // ----- Q13 — TRIG / material support (T-visa) -----
  T_SUBST_TRIG_RISK: "T_SUBST_TRIG_RISK",

  // ----- Q14 — Prior false claim to U.S. citizenship -----
  T_SUBST_FALSE_CLAIM_RISK: "T_SUBST_FALSE_CLAIM_RISK",
  U_SUBST_FALSE_CLAIM_RISK: "U_SUBST_FALSE_CLAIM_RISK",
  V_SUBST_FALSE_CLAIM_RISK: "V_SUBST_FALSE_CLAIM_RISK",

  // ----- Parte 6 (Flavia) — A-number sem carta de imigração -----
  // Cliente VAWA/U-visa tem A-number preenchido em algum form mas nao foi
  // detectada carta de imigração entre os documentos. Sinaliza pra cruzar
  // com EOIR antes do filing.
  IMM_EWI_A_NUMBER_NO_IMMIGRATION_DOC: "IMM_EWI_A_NUMBER_NO_IMMIGRATION_DOC",

  // ----- Requisição 05/06 (Flavia/Yuri) -----
  // Bar Number do advogado deve ser o esperado (5794276) em todos os documentos.
  T_FILING_ATTORNEY_BAR_DIVERGE: "T_FILING_ATTORNEY_BAR_DIVERGE",
  // Página de Final Considerations sem assinatura do advogado.
  T_FILING_FINAL_ATTORNEY_SIG_MISSING: "T_FILING_FINAL_ATTORNEY_SIG_MISSING",
  // Seção listada na Table of Contents sem divisória/seção detectada no processo.
  T_FILING_TOC_SECTION_MISSING: "T_FILING_TOC_SECTION_MISSING"
} as const;

export type RuleId = keyof typeof RULE_IDS;
